extends: default

locale: en_US.UTF-8
rules:
  document-start: enable
  key-ordering: enable
  line-length:
    max: 512
  octal-values: enable
  quoted-strings:
    check-keys: true
    required: only-when-needed
